org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1
minecraft_version_range=[26.1,26.1.3)
minecraft_version_range_label=26.1-26.1.2
forge_version=62.0.9
forge_version_range=[62,65)
loader_version_range=[62,65)
mapping_channel=official
mapping_version=26.1

mod_id=linearreader
mod_name=LinearReader
mod_license=MIT
mod_version=1.2.0
mod_group_id=com.bugfunbug.linearreader
mod_authors=Bugfunbug
mod_description=A mod that utilizes .linear compression to reduce the file size of your world.