package com.bugfunbug.linearreader.linear;

import com.bugfunbug.linearreader.LinearReader;
import com.bugfunbug.linearreader.LinearStats;
import com.bugfunbug.linearreader.config.LinearConfig;
import com.github.luben.zstd.Zstd;
import net.minecraft.world.level.ChunkPos;
import org.jetbrains.annotations.Nullable;

import java.io.*;
import java.nio.ByteBuffer;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.Collections;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.locks.ReentrantReadWriteLock;
import java.util.zip.CRC32;

public class LinearRegionFile {

    /** Every LinearRegionFile that is currently open. Used for flush-on-save and the info command. */
    public static final Set<LinearRegionFile> ALL_OPEN =
            Collections.newSetFromMap(new ConcurrentHashMap<>());

    private static final long LINEAR_SIGNATURE  = 0xc3ff13183cca9d9aL;
    private static final byte LINEAR_VERSION    = 1;
    private static final int  REGION_DIM        = 32;
    private static final int  CHUNK_COUNT       = REGION_DIM * REGION_DIM; // 1024
    private static final int  INNER_HEADER_SIZE = CHUNK_COUNT * 8;         // 8192 bytes

    // Outer file header layout (32 bytes total):
    //   0  –  7 : LINEAR_SIGNATURE  (long)
    //   8        : version           (byte)
    //   9  – 16 : newest timestamp  (long)
    //  17        : compression level (byte)
    //  18 – 19  : chunk count       (short)
    //  20 – 23  : compressed length (int)
    //  24 – 31  : CRC32 of compressed body as long (upper 32 bits = 0); 0 = no checksum

    // One CRC32 per thread — avoids allocating a new CRC32 on every flush/verify.
    private static final ThreadLocal<CRC32> TL_CRC32 = ThreadLocal.withInitial(CRC32::new);

    // Add this static executor near the top of the class, alongside TL_CRC32 etc.
    /**
     * Single-thread executor for backup writes.
     * Backups run at a higher compression level than live files, so write time is
     * significant — pushing them off the flush thread eliminates flush latency spikes.
     */
    private static final java.util.concurrent.ExecutorService BACKUP_EXECUTOR =
            java.util.concurrent.Executors.newSingleThreadExecutor(r -> {
                Thread t = new Thread(r, "lr-backup");
                t.setDaemon(true);
                t.setPriority(Thread.MIN_PRIORITY + 1);
                return t;
            });

    /** Compression level for .bak files — higher than live since write speed is irrelevant. */
    private static final int BACKUP_COMPRESSION_LEVEL = 22;

    // Reusable byte-array buffers per flush thread — dramatically reduces GC pressure
    // under heavy worldgen where flushes happen constantly.
    private static final ThreadLocal<byte[][]> TL_FLUSH_BUFS =
            ThreadLocal.withInitial(() -> new byte[2][]);

    // Throttle the disk-space syscall to at most once per minute per flush thread.
    private static final ThreadLocal<Long> TL_LAST_DISK_CHECK =
            ThreadLocal.withInitial(() -> 0L);

    // Read-write lock: multiple threads can read chunks concurrently; writes are exclusive.
    private final ReentrantReadWriteLock lock = new ReentrantReadWriteLock();

    private final Path    path;
    private final boolean dsync;

    public final int regionX;
    public final int regionZ;

    private final byte[][] chunkData  = new byte[CHUNK_COUNT][];
    private final int[]    timestamps = new int[CHUNK_COUNT];

    // Running counters updated incrementally on every chunk write,
    // eliminating the O(1024) scans the original code did on every flush.
    private int  chunkCount      = 0;
    private long totalDataBytes  = 0L;
    private long newestTimestamp = 0L;

    // volatile so isDirty() is always fresh across threads without a lock.
    private volatile boolean dirty = false;

    private int     saveCount = 0;
    private boolean backedUp  = false;

    public LinearRegionFile(Path path, boolean dsync) throws IOException {
        this.path  = path;
        this.dsync = dsync;

        String[] parts = path.getFileName().toString().split("\\.");
        this.regionX = Integer.parseInt(parts[1]);
        this.regionZ = Integer.parseInt(parts[2]);

        if (Files.exists(path)) {
            boolean loaded = tryLoadOrRecover();
            if (!loaded) {
                LinearReader.LOGGER.error(
                        "[LinearReader] r.{}.{}.linear could not be recovered. " +
                                "The region will be regenerated by Minecraft.", regionX, regionZ);
            } else if (DHPregenMonitor.isBackupEnabled()) {
                // Skip initial backup creation when DH pregen is already running —
                // we'd only be backing up a file we're about to overwrite heavily.
                createBackupIfAbsent();
            }
        }

        ALL_OPEN.add(this);
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    private static int indexOf(ChunkPos pos) {
        return (pos.x & 31) + (pos.z & 31) * REGION_DIM;
    }

    public boolean hasChunk(ChunkPos pos) {
        lock.readLock().lock();
        try {
            byte[] d = chunkData[indexOf(pos)];
            return d != null && d.length > 0;
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Removes a chunk entry from this region.
     * Called when c2me's backlog flush invokes RegionFile.clear(ChunkPos).
     */
    public void clearChunk(ChunkPos pos) {
        lock.writeLock().lock();
        try {
            int    idx = indexOf(pos);
            byte[] old = chunkData[idx];
            if (old != null && old.length > 0) {
                chunkData[idx] = null;
                chunkCount--;
                totalDataBytes -= old.length;
                dirty = true;
            }
        } finally {
            lock.writeLock().unlock();
        }
    }

    @Nullable
    public DataInputStream read(ChunkPos pos) {
        lock.readLock().lock();
        try {
            byte[] d = chunkData[indexOf(pos)];
            if (d == null || d.length == 0) return null;

            // Record the read here rather than in the mixin so C2ME's async
            // read path gets counted too. The "work" being timed is the
            // array copy inside ByteArrayInputStream's constructor + the
            // DataInputStream wrapper — negligible but consistent.
            long t = System.nanoTime();
            DataInputStream dis = new DataInputStream(new ByteArrayInputStream(d));
            LinearStats.recordChunkRead(System.nanoTime() - t);
            return dis;
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Returns a DataOutputStream that commits chunk data into this region when closed.
     * NBT serialisation happens entirely outside any lock; the write lock is taken
     * only for the brief pointer-swap at the end of close().
     */
    public DataOutputStream write(ChunkPos pos) {
        final int idx = indexOf(pos);

        // Racy read is intentional — only a capacity hint for the BAOS.
        byte[] prev = chunkData[idx];
        int hint = (prev != null && prev.length > 0) ? prev.length : 8192;

        ByteArrayOutputStream boas = new ByteArrayOutputStream(hint) {
            @Override
            public void close() throws IOException {
                super.close();
                byte[] newData = toByteArray();
                int ts = (int) (System.currentTimeMillis() / 1000L);
                lock.writeLock().lock();
                try {
                    byte[] old   = chunkData[idx];
                    int    oldLen = (old != null) ? old.length : 0;

                    chunkData[idx]  = newData;
                    timestamps[idx] = ts;
                    if (ts > newestTimestamp) newestTimestamp = ts;

                    if (oldLen == 0 && newData.length > 0) chunkCount++;
                    else if (oldLen > 0 && newData.length == 0) chunkCount--;
                    totalDataBytes += newData.length - oldLen;

                    dirty = true;
                } finally {
                    lock.writeLock().unlock();
                }
            }
        };
        return new DataOutputStream(boas);
    }

    /**
     * Flushes this region to disk if dirty.
     *
     * The data snapshot is taken under the write lock, the lock is released, and
     * the heavy compression + I/O work proceeds lock-free.  This lets concurrent
     * chunk reads and writes continue while a flush is in progress.
     */
    public void flush() throws IOException {
        if (!dirty) return; // fast volatile read before acquiring any lock

        final byte[][] dataSnap;
        final int[]    tsSnap;
        final long     newestTsSnap;
        final int      countSnap;
        final long     totalBytesSnap;

        lock.writeLock().lock();
        try {
            if (!dirty) return; // double-check after lock
            dataSnap       = chunkData.clone();  // shallow: copies 1024 refs (8 KB)
            tsSnap         = timestamps.clone();
            newestTsSnap   = newestTimestamp;
            countSnap      = chunkCount;
            totalBytesSnap = totalDataBytes;
            dirty          = false;
        } finally {
            lock.writeLock().unlock();
        }

        boolean ioOk = false;
        try {
            writeToDisk(dataSnap, tsSnap, newestTsSnap, countSnap, totalBytesSnap);
            ioOk = true;
        } finally {
            if (!ioOk) {
                lock.writeLock().lock();
                try { dirty = true; } finally { lock.writeLock().unlock(); }
            }
        }

        // Post-I/O bookkeeping — use DHPregenMonitor so backups are suppressed during pregen.
        final boolean shouldRefreshBackup;
        lock.writeLock().lock();
        try {
            saveCount++;
            shouldRefreshBackup = DHPregenMonitor.isBackupEnabled()
                    && saveCount % LinearConfig.getBackupUpdateInterval() == 0;
        } finally {
            lock.writeLock().unlock();
        }

        if (shouldRefreshBackup) refreshBackup();
    }

    public void close() throws IOException {
        ALL_OPEN.remove(this);
        flush();
    }

    /**
     * Releases all chunk byte arrays so the GC can reclaim the NBT payload.
     *
     * <b>Call only after the region has been flushed to disk and evicted from
     * {@code linearCache}</b> — i.e. from {@link com.bugfunbug.linearreader.LinearReader#submitFlush}
     * after the flush task completes.  Calling this on a live cache entry would
     * cause NPEs on the next read of any chunk in the region.
     *
     * During DH pregen the cache is kept at 8 entries, so regions are evicted
     * and flushed frequently.  Without this call each flushed region's ~8 MB of
     * NBT data would sit in old-gen until the next full GC — enough to trigger
     * multi-second GC pauses that the watchdog mistakes for a server hang.
     */
    public void releaseChunkData() {
        lock.writeLock().lock();
        try {
            Arrays.fill(chunkData, null);
            chunkCount     = 0;
            totalDataBytes = 0L;
        } finally {
            lock.writeLock().unlock();
        }
    }

    /** O(1) — backed by a running counter. */
    public long estimateRamBytes() {
        return totalDataBytes;
    }

    public Path    getPath()  { return path; }
    public boolean isDirty()  { return dirty; }

    @Override
    public String toString() {
        return "LinearRegionFile{r." + regionX + "." + regionZ + ", dirty=" + dirty + "}";
    }

    // -------------------------------------------------------------------------
    // Corruption recovery
    // -------------------------------------------------------------------------

    private boolean tryLoadOrRecover() {
        try {
            loadFromDisk(path);
            return true;
        } catch (IOException primaryEx) {
            LinearReader.LOGGER.error(
                    "[LinearReader] Failed to load {}: {}", path.getFileName(), primaryEx.getMessage());
        }

        // ── Quarantine the corrupt file ───────────────────────────────────────
        // Include a timestamp so multiple corruptions of the same region don't
        // overwrite each other in the quarantine folder.
        String timestamp = java.time.LocalDateTime.now()
                .format(java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"));
        Path quarantineDir  = path.getParent().resolve("corrupted");
        String corruptName  = "r." + regionX + "." + regionZ
                + "-" + timestamp + ".corrupt.linear";
        Path quarantinePath = quarantineDir.resolve(corruptName);

        try {
            Files.createDirectories(quarantineDir);
            Files.move(path, quarantinePath, StandardCopyOption.REPLACE_EXISTING);
            LinearReader.LOGGER.error(
                    "[LinearReader] Quarantined corrupt file -> corrupted/{} " +
                            "(keep this for debugging, it is safe to delete)", corruptName);
        } catch (IOException moveEx) {
            LinearReader.LOGGER.error(
                    "[LinearReader] Could not quarantine {}: {}",
                    path.getFileName(), moveEx.getMessage());
        }

        // ── Try backup ────────────────────────────────────────────────────────
        Path bak = bakPath();
        if (Files.exists(bak)) {
            try {
                loadFromDisk(bak);
                LinearReader.LOGGER.warn(
                        "[LinearReader] Recovered r.{}.{}.linear from backup (.bak). " +
                                "Chunks modified since the last backup will be regenerated.",
                        regionX, regionZ);
                dirty = true;
                return true;
            } catch (IOException bakEx) {
                LinearReader.LOGGER.error(
                        "[LinearReader] Backup is also corrupt: {}", bakEx.getMessage());
                // Quarantine the bad backup too so it doesn't cause confusion.
                String bakCorruptName = "r." + regionX + "." + regionZ
                        + "-" + timestamp + "-backup.corrupt.linear";
                try {
                    Files.move(bak, quarantineDir.resolve(bakCorruptName),
                            StandardCopyOption.REPLACE_EXISTING);
                    LinearReader.LOGGER.error(
                            "[LinearReader] Quarantined corrupt backup -> corrupted/{}",
                            bakCorruptName);
                } catch (IOException ignored) {}
            }
        } else {
            LinearReader.LOGGER.error(
                    "[LinearReader] No backup found for r.{}.{}.linear. " +
                            "Enable backupEnabled=true in linearreader-server.toml to protect against this.",
                    regionX, regionZ);
        }

        return false;
    }

    // -------------------------------------------------------------------------
    // Disk I/O
    // -------------------------------------------------------------------------

    private void loadFromDisk(Path src) throws IOException {
        long startNs = System.nanoTime();

        byte[] raw = Files.readAllBytes(src);

        if (raw.length < 40)
            throw new IOException("[LinearReader] File too short (" + raw.length + " bytes): " + src);

        ByteBuffer hdr    = ByteBuffer.wrap(raw, 0, 32);
        long  sig         = hdr.getLong();
        byte  version     = hdr.get();
        long  newestTs    = hdr.getLong();
        hdr.get();                            // compression level (not needed for decompression)
        short storedCount = hdr.getShort();
        hdr.getInt();                         // compressed-body length (we use actual file length)
        long  storedCRC   = hdr.getLong();

        if (sig != LINEAR_SIGNATURE)
            throw new IOException("[LinearReader] Bad header signature in: " + src);
        if (version != LINEAR_VERSION)
            throw new IOException("[LinearReader] Unsupported version " + version + " in: " + src);
        if (ByteBuffer.wrap(raw, raw.length - 8, 8).getLong() != LINEAR_SIGNATURE)
            throw new IOException("[LinearReader] Bad footer signature in: " + src);

        int compressedBodyLength = raw.length - 40;
        if (compressedBodyLength <= 0)
            throw new IOException("[LinearReader] No compressed body in: " + src);

        if (storedCRC != 0L) {
            CRC32 crc = TL_CRC32.get();
            crc.reset();
            crc.update(raw, 32, compressedBodyLength);
            if (crc.getValue() != storedCRC)
                throw new IOException("[LinearReader] CRC32 checksum mismatch in: " + src
                        + " (expected " + storedCRC + ", got " + crc.getValue() + ")");
        }

        byte[] compressed = new byte[compressedBodyLength];
        System.arraycopy(raw, 32, compressed, 0, compressedBodyLength);

        long expectedDecompSize = Zstd.decompressedSize(compressed);
        if (expectedDecompSize <= 0 || expectedDecompSize > Integer.MAX_VALUE)
            throw new IOException("[LinearReader] Cannot determine decompressed size in: " + src);

        byte[] decompressed = new byte[(int) expectedDecompSize];
        long result = Zstd.decompress(decompressed, compressed);
        if (Zstd.isError(result))
            throw new IOException("[LinearReader] Zstd error (" + Zstd.getErrorName(result) + ") in: " + src);
        if (result != expectedDecompSize)
            throw new IOException("[LinearReader] Decompressed size mismatch in: " + src);

        if (decompressed.length < INNER_HEADER_SIZE)
            throw new IOException("[LinearReader] Decompressed body too short in: " + src);

        ByteBuffer inner  = ByteBuffer.wrap(decompressed, 0, INNER_HEADER_SIZE);
        int[]      sizes  = new int[CHUNK_COUNT];
        int        totalSz    = 0;
        int        realCount  = 0;
        for (int i = 0; i < CHUNK_COUNT; i++) {
            sizes[i]      = inner.getInt();
            timestamps[i] = inner.getInt();
            totalSz      += sizes[i];
            if (sizes[i] > 0) realCount++;
        }

        if (INNER_HEADER_SIZE + totalSz != decompressed.length)
            throw new IOException("[LinearReader] Inner size mismatch in: " + src
                    + " (expected " + (INNER_HEADER_SIZE + totalSz) + ", got " + decompressed.length + ")");

        if (realCount != storedCount)
            throw new IOException("[LinearReader] Chunk count mismatch in: " + src
                    + " (header says " + storedCount + ", counted " + realCount + ")");

        int offset = INNER_HEADER_SIZE;
        for (int i = 0; i < CHUNK_COUNT; i++) {
            if (sizes[i] > 0) {
                chunkData[i] = new byte[sizes[i]];
                System.arraycopy(decompressed, offset, chunkData[i], 0, sizes[i]);
            }
            offset += sizes[i];
        }

        this.newestTimestamp = newestTs;
        this.chunkCount      = realCount;
        this.totalDataBytes  = totalSz;

        long elapsedNs = System.nanoTime() - startNs;
        long elapsedMs = elapsedNs / 1_000_000L;
        LinearStats.recordRegionLoad(elapsedNs);
        int  threshold = LinearConfig.getSlowIoThresholdMs();
        if (threshold >= 0 && elapsedMs > threshold) {
            LinearReader.LOGGER.warn(
                    "[LinearReader] Slow region load: {} took {}ms (threshold {}ms). " +
                            "Check disk health or lower regionCacheSize.",
                    src.getFileName(), elapsedMs, threshold);
        } else {
            LinearReader.LOGGER.debug("[LinearReader] Loaded {} in {}ms.", src.getFileName(), elapsedMs);
        }
    }

    /**
     * Serializes and atomically writes a data snapshot to disk.
     * Called from flush() after the lock has been released.
     */
    private void writeToDisk(byte[][] dataSnap, int[] tsSnap,
                             long newestTsSnap, int countSnap, long totalBytesSnap)
            throws IOException {

        Files.createDirectories(path.getParent());

        int warnGb = LinearConfig.getDiskSpaceWarnGb();
        if (warnGb >= 0) {
            long nowMs = System.currentTimeMillis();
            if (nowMs - TL_LAST_DISK_CHECK.get() > 60_000L) {
                TL_LAST_DISK_CHECK.set(nowMs);
                try {
                    long freeBytes = Files.getFileStore(path.getParent()).getUsableSpace();
                    if (freeBytes < (long) warnGb * 1024L * 1024L * 1024L) {
                        LinearReader.LOGGER.warn(
                                "[LinearReader] Low disk space: {} GB free (threshold {} GB). " +
                                        "A full disk during a region save can cause corruption!",
                                String.format("%.2f", freeBytes / (1024.0 * 1024.0 * 1024.0)), warnGb);
                    }
                } catch (IOException e) {
                    LinearReader.LOGGER.warn("[LinearReader] Could not check disk space: {}", e.getMessage());
                }
            }
        }

        long startNs = System.nanoTime();
        int compressionLevel = LinearConfig.getCompressionLevel();

        int totalBytes = (int) totalBytesSnap;
        int bodySize   = INNER_HEADER_SIZE + totalBytes;

        byte[][] bufs = TL_FLUSH_BUFS.get();
        if (bufs[0] == null || bufs[0].length != bodySize)
            bufs[0] = new byte[bodySize];
        byte[] body = bufs[0];

        ByteBuffer bodyBuf = ByteBuffer.wrap(body, 0, bodySize);
        for (int i = 0; i < CHUNK_COUNT; i++) {
            bodyBuf.putInt(dataSnap[i] != null ? dataSnap[i].length : 0);
            bodyBuf.putInt(tsSnap[i]);
        }
        for (int i = 0; i < CHUNK_COUNT; i++) {
            if (dataSnap[i] != null) bodyBuf.put(dataSnap[i]);
        }

        int    maxCompLen    = (int) Zstd.compressBound(bodySize);
        if (bufs[1] == null || bufs[1].length < maxCompLen)
            bufs[1] = new byte[maxCompLen];
        byte[] compressedBuf = bufs[1];

        long   compLen       = Zstd.compress(compressedBuf, body, compressionLevel);
        if (Zstd.isError(compLen))
            throw new IOException("[LinearReader] Zstd compression error: " + Zstd.getErrorName(compLen));

        CRC32 crc = TL_CRC32.get();
        crc.reset();
        crc.update(compressedBuf, 0, (int) compLen);
        long checksum = crc.getValue();

        byte[]     out    = new byte[32 + (int) compLen + 8];
        ByteBuffer outBuf = ByteBuffer.wrap(out);
        outBuf.putLong(LINEAR_SIGNATURE);
        outBuf.put(LINEAR_VERSION);
        outBuf.putLong(newestTsSnap);
        outBuf.put((byte) compressionLevel);
        outBuf.putShort((short) countSnap);
        outBuf.putInt((int) compLen);
        outBuf.putLong(checksum);
        outBuf.put(compressedBuf, 0, (int) compLen);
        outBuf.putLong(LINEAR_SIGNATURE);

        Path wip = path.resolveSibling(path.getFileName() + ".wip");
        Files.write(wip, out);

        if (dsync) {
            try (FileOutputStream fos = new FileOutputStream(wip.toFile(), true)) {
                fos.getFD().sync();
            }
        }

        try {
            Files.move(wip, path, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (AtomicMoveNotSupportedException e) {
            Files.move(wip, path, StandardCopyOption.REPLACE_EXISTING);
        }

        long elapsedNs = System.nanoTime() - startNs;
        long elapsedMs = elapsedNs / 1_000_000L;
        LinearStats.recordRegionFlush(elapsedNs, bodySize, compLen);
        int  threshold = LinearConfig.getSlowIoThresholdMs();
        if (threshold >= 0 && elapsedMs > threshold) {
            LinearReader.LOGGER.warn(
                    "[LinearReader] Slow region save: r.{}.{}.linear took {}ms (threshold {}ms). " +
                            "Check disk health.", regionX, regionZ, elapsedMs, threshold);
        }
    }

    // -------------------------------------------------------------------------
    // Backup helpers
    // -------------------------------------------------------------------------

    private Path bakPath() {
        return path.resolveSibling(path.getFileName() + ".bak");
    }

    private void createBackupIfAbsent() {
        if (backedUp) return;
        backedUp = true; // set eagerly so concurrent flushes don't double-submit
        Path bak = bakPath();
        if (Files.exists(bak)) return;
        final Path src = path;
        BACKUP_EXECUTOR.submit(() -> {
            try {
                IdleRecompressor.recompressFileTo(src, bak, BACKUP_COMPRESSION_LEVEL);
                LinearReader.LOGGER.debug("[LinearReader] Created backup: {}", bak.getFileName());
            } catch (IOException e) {
                LinearReader.LOGGER.warn("[LinearReader] Could not create backup for {}: {}",
                        src.getFileName(), e.getMessage());
                backedUp = false; // allow retry on next flush
            }
        });
    }

    private void refreshBackup() {
        Path bak = bakPath();
        final Path src = path;
        BACKUP_EXECUTOR.submit(() -> {
            try {
                IdleRecompressor.recompressFileTo(src, bak, BACKUP_COMPRESSION_LEVEL);
                LinearReader.LOGGER.debug("[LinearReader] Refreshed backup: {} (after {} saves)",
                        bak.getFileName(), saveCount);
            } catch (IOException e) {
                LinearReader.LOGGER.warn("[LinearReader] Could not refresh backup for {}: {}",
                        src.getFileName(), e.getMessage());
            }
        });
    }

    // -------------------------------------------------------------------------
    // Static utility: verify a file on disk without opening it as a region.
    // -------------------------------------------------------------------------

    public static VerifyResult verifyOnDisk(Path file) {
        try {
            byte[] raw = Files.readAllBytes(file);

            if (raw.length < 40)
                return VerifyResult.fail("file too short (" + raw.length + " bytes)");

            ByteBuffer hdr  = ByteBuffer.wrap(raw, 0, 32);
            long sig        = hdr.getLong();
            byte version    = hdr.get();
            hdr.getLong();  // newest timestamp
            hdr.get();      // compression level
            hdr.getShort(); // chunk count
            hdr.getInt();   // compressed length
            long storedCRC  = hdr.getLong();

            if (sig != LINEAR_SIGNATURE)
                return VerifyResult.fail("bad header signature");
            if (version != LINEAR_VERSION)
                return VerifyResult.fail("unsupported version: " + version);
            if (ByteBuffer.wrap(raw, raw.length - 8, 8).getLong() != LINEAR_SIGNATURE)
                return VerifyResult.fail("bad footer signature");

            if (storedCRC != 0L) {
                int compLen = raw.length - 40;
                if (compLen <= 0)
                    return VerifyResult.fail("no compressed body");
                CRC32 crc = TL_CRC32.get();
                crc.reset();
                crc.update(raw, 32, compLen);
                if (crc.getValue() != storedCRC)
                    return VerifyResult.fail(
                            "CRC32 mismatch (expected " + storedCRC + ", got " + crc.getValue() + ")");
            }

            // was: return VerifyResult.ok();
            return VerifyResult.ok(storedCRC != 0L);
        } catch (IOException e) {
            return VerifyResult.fail("I/O error: " + e.getMessage());
        }
    }

    public static class VerifyResult {
        public final boolean ok;
        public final boolean hasCRC;  // false = Python-written or pre-1.0 file (no checksum)
        public final String  reason;

        private VerifyResult(boolean ok, boolean hasCRC, String reason) {
            this.ok     = ok;
            this.hasCRC = hasCRC;
            this.reason = reason;
        }
        static VerifyResult ok(boolean hasCRC)   { return new VerifyResult(true,  hasCRC, null); }
        static VerifyResult fail(String why)     { return new VerifyResult(false, false,  why);  }
    }

    /**
     * Shuts down the backup executor on server stop.
     * Waits up to 30 seconds for any in-flight backup writes to finish
     * so we don't leave partial .bak files on disk.
     */
    public static void shutdownBackupExecutor() {
        BACKUP_EXECUTOR.shutdown();
        try {
            if (!BACKUP_EXECUTOR.awaitTermination(30, java.util.concurrent.TimeUnit.SECONDS)) {
                LinearReader.LOGGER.warn("[LinearReader] Backup executor did not finish within 30s on shutdown.");
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}